GET http://localhost:7777/books/

###


GET http://localhost:7777/books/:5/

###


POST http://localhost:7777/books/
Content-Type: application/json

{
  "title": " Potter and the Order of the Phoenix",
  "authorId": 1,
  "rating": 4.62,
  "ratingCount": 126559,
  "reviewCount": 711,
  "description": "There is a door at the end of a silent corridor.",
  "pages": 352,
  "dateOfPublication": "May 1st 2003",
  "editionLanguage": "English",
  "price": 1000,
  "onlineStores": "Amazon,Audible,Indigo,Apple Books,Google Play,IndieBound"
}

###


PUT http://localhost:7777/books/41/
Content-Type: application/json

{
  "title": "Harry Potter and the Order of the Phoenix",
  "authorId": 1,
  "rating": 5,
  "ratingCount": 1000000,
  "reviewCount": 711,
  "description": "There is a door at the end of a silent corridor.",
  "pages": 352,
  "dateOfPublication": "May 1st 2003",
  "editionLanguage": "English",
  "price": 850,
  "onlineStores": "Amazon,Audible,Indigo,Apple Books,Google Play,IndieBound"
}

###


DELETE http://localhost:7777/books/22/

###


GET http://localhost:7777/authors/1/books/


###


GET http://localhost:7777/filteredBooks/?offset=2&limit=3&search_q=potter&order_by=price&order=DESC


###


###



//// Authentication ////
POST http://localhost:7777/users/
Content-Type: application/json

{   
    "name":"swarna",
    "username":"swarnateja",
    "password": "swarna@456",
    "gender": "Male",
    "location":"vizag"
}


###

POST http://localhost:7777/login/
Content-Type: application/json

{
    "username":"swarnateja",
    "password": "swarna@456"
}

###

POST http://localhost:7777/loginJwt/
Content-Type: application/json

{
    "username":"swarnateja",
    "password": "swarna@456"
}


###


GET http://localhost:7777/booksJwt/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjQ3MDY3ODcyfQ.sgbYlH_5juembMwO9cKsnaqKmW9Wr4-0VIyrG2T3aGw
###


GET http://localhost:7777/booksJwt/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjQ3MDY3ODcyfQ.sgbYlH_5juembMwO9cKsnaqKmW9Wr4-0VIyrG2T3aGw

###


GET http://localhost:7777/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN3YXJuYXRlamEiLCJpYXQiOjE2NDcxMTA3Njl9.TPz6HEoqFQo72qWEraYSewe8kDkn1D2m5C2_rqAPK0Q
###